// @TODO: Should remove unused/redundant variables

export const CATEGORY_HERO_ASPECT_RATIO = '16:9'
export const CATEGORY_HERO_ASPECT_RATIO_MULTIPLIER = 9 / 16
export const CATEGORY_HERO_WIDTH = 256
export const CATEGORY_HERO_HEIGHT = 144
export const CATEGORY_HERO_X_TOTAL_PADDING = 16
export const CATEGORY_HERO_Y_TOTAL_PADDING = 32
export const CATEGORY_HERO_TOTAL_WIDTH = CATEGORY_HERO_WIDTH + CATEGORY_HERO_X_TOTAL_PADDING
export const CATEGORY_HERO_TOTAL_HEIGHT = CATEGORY_HERO_HEIGHT + CATEGORY_HERO_Y_TOTAL_PADDING
export const CATEGORY_HERO_CONTAINER_PADDING = 16

export const CATEGORY_HERO_INITIAL_COUNT = 3
export const CATEGORY_ROW_WIDTH = CATEGORY_HERO_TOTAL_WIDTH * (CATEGORY_HERO_INITIAL_COUNT + 1) // The + 1 comes from the "new" placeholder
export const CATEGORY_ROW_HEIGHT = CATEGORY_HERO_HEIGHT + CATEGORY_HERO_Y_TOTAL_PADDING
export const CATEGORY_BODY_INITIAL_WIDTH = CATEGORY_ROW_WIDTH + CATEGORY_HERO_Y_TOTAL_PADDING
export const CATEGORY_BODY_INITIAL_HEIGHT = CATEGORY_ROW_HEIGHT + CATEGORY_HERO_Y_TOTAL_PADDING

export const CATEGORY_SPACING = 96

export const ORDER_FIRST_BUFFER = 0
export const ORDER_LAST_BUFFER = 1024
