<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Str;
use App\Models\Hero;

return new class extends Migration
{
    // Generated by `artisan smarf:hero`
    protected $updated = [
        [
            "name" => "Anti-Mage",
            "attribute" => "agility",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/antimage.png"
        ],
        [
            "name" => "Axe",
            "attribute" => "strength",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/axe.png"
        ],
        [
            "name" => "Bane",
            "attribute" => "intelligence",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/bane.png"
        ],
        [
            "name" => "Bloodseeker",
            "attribute" => "agility",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/bloodseeker.png"
        ],
        [
            "name" => "Crystal Maiden",
            "attribute" => "intelligence",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/crystal_maiden.png"
        ],
        [
            "name" => "Drow Ranger",
            "attribute" => "agility",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/drow_ranger.png"
        ],
        [
            "name" => "Earthshaker",
            "attribute" => "strength",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/earthshaker.png"
        ],
        [
            "name" => "Juggernaut",
            "attribute" => "agility",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/juggernaut.png"
        ],
        [
            "name" => "Mirana",
            "attribute" => "agility",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/mirana.png"
        ],
        [
            "name" => "Morphling",
            "attribute" => "agility",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/morphling.png"
        ],
        [
            "name" => "Shadow Fiend",
            "attribute" => "agility",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/nevermore.png"
        ],
        [
            "name" => "Phantom Lancer",
            "attribute" => "agility",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/phantom_lancer.png"
        ],
        [
            "name" => "Puck",
            "attribute" => "intelligence",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/puck.png"
        ],
        [
            "name" => "Pudge",
            "attribute" => "strength",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/pudge.png"
        ],
        [
            "name" => "Razor",
            "attribute" => "agility",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/razor.png"
        ],
        [
            "name" => "Sand King",
            "attribute" => "strength",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/sand_king.png"
        ],
        [
            "name" => "Storm Spirit",
            "attribute" => "intelligence",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/storm_spirit.png"
        ],
        [
            "name" => "Sven",
            "attribute" => "strength",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/sven.png"
        ],
        [
            "name" => "Tiny",
            "attribute" => "strength",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/tiny.png"
        ],
        [
            "name" => "Vengeful Spirit",
            "attribute" => "agility",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/vengefulspirit.png"
        ],
        [
            "name" => "Windranger",
            "attribute" => "intelligence",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/windrunner.png"
        ],
        [
            "name" => "Zeus",
            "attribute" => "intelligence",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/zuus.png"
        ],
        [
            "name" => "Kunkka",
            "attribute" => "strength",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/kunkka.png"
        ],
        [
            "name" => "Lina",
            "attribute" => "intelligence",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/lina.png"
        ],
        [
            "name" => "Lion",
            "attribute" => "intelligence",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/lion.png"
        ],
        [
            "name" => "Shadow Shaman",
            "attribute" => "intelligence",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/shadow_shaman.png"
        ],
        [
            "name" => "Slardar",
            "attribute" => "strength",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/slardar.png"
        ],
        [
            "name" => "Tidehunter",
            "attribute" => "strength",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/tidehunter.png"
        ],
        [
            "name" => "Witch Doctor",
            "attribute" => "intelligence",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/witch_doctor.png"
        ],
        [
            "name" => "Lich",
            "attribute" => "intelligence",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/lich.png"
        ],
        [
            "name" => "Riki",
            "attribute" => "agility",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/riki.png"
        ],
        [
            "name" => "Enigma",
            "attribute" => "intelligence",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/enigma.png"
        ],
        [
            "name" => "Tinker",
            "attribute" => "intelligence",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/tinker.png"
        ],
        [
            "name" => "Sniper",
            "attribute" => "agility",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/sniper.png"
        ],
        [
            "name" => "Necrophos",
            "attribute" => "intelligence",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/necrolyte.png"
        ],
        [
            "name" => "Warlock",
            "attribute" => "intelligence",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/warlock.png"
        ],
        [
            "name" => "Beastmaster",
            "attribute" => "strength",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/beastmaster.png"
        ],
        [
            "name" => "Queen of Pain",
            "attribute" => "intelligence",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/queenofpain.png"
        ],
        [
            "name" => "Venomancer",
            "attribute" => "agility",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/venomancer.png"
        ],
        [
            "name" => "Faceless Void",
            "attribute" => "agility",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/faceless_void.png"
        ],
        [
            "name" => "Wraith King",
            "attribute" => "strength",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/skeleton_king.png"
        ],
        [
            "name" => "Death Prophet",
            "attribute" => "intelligence",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/death_prophet.png"
        ],
        [
            "name" => "Phantom Assassin",
            "attribute" => "agility",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/phantom_assassin.png"
        ],
        [
            "name" => "Pugna",
            "attribute" => "intelligence",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/pugna.png"
        ],
        [
            "name" => "Templar Assassin",
            "attribute" => "agility",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/templar_assassin.png"
        ],
        [
            "name" => "Viper",
            "attribute" => "agility",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/viper.png"
        ],
        [
            "name" => "Luna",
            "attribute" => "agility",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/luna.png"
        ],
        [
            "name" => "Dragon Knight",
            "attribute" => "strength",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/dragon_knight.png"
        ],
        [
            "name" => "Dazzle",
            "attribute" => "intelligence",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/dazzle.png"
        ],
        [
            "name" => "Clockwerk",
            "attribute" => "strength",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/rattletrap.png"
        ],
        [
            "name" => "Leshrac",
            "attribute" => "intelligence",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/leshrac.png"
        ],
        [
            "name" => "Nature's Prophet",
            "attribute" => "intelligence",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/furion.png"
        ],
        [
            "name" => "Lifestealer",
            "attribute" => "strength",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/life_stealer.png"
        ],
        [
            "name" => "Dark Seer",
            "attribute" => "intelligence",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/dark_seer.png"
        ],
        [
            "name" => "Clinkz",
            "attribute" => "agility",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/clinkz.png"
        ],
        [
            "name" => "Omniknight",
            "attribute" => "strength",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/omniknight.png"
        ],
        [
            "name" => "Enchantress",
            "attribute" => "intelligence",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/enchantress.png"
        ],
        [
            "name" => "Huskar",
            "attribute" => "strength",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/huskar.png"
        ],
        [
            "name" => "Night Stalker",
            "attribute" => "strength",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/night_stalker.png"
        ],
        [
            "name" => "Broodmother",
            "attribute" => "agility",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/broodmother.png"
        ],
        [
            "name" => "Bounty Hunter",
            "attribute" => "agility",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/bounty_hunter.png"
        ],
        [
            "name" => "Weaver",
            "attribute" => "agility",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/weaver.png"
        ],
        [
            "name" => "Jakiro",
            "attribute" => "intelligence",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/jakiro.png"
        ],
        [
            "name" => "Batrider",
            "attribute" => "intelligence",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/batrider.png"
        ],
        [
            "name" => "Chen",
            "attribute" => "intelligence",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/chen.png"
        ],
        [
            "name" => "Spectre",
            "attribute" => "agility",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/spectre.png"
        ],
        [
            "name" => "Ancient Apparition",
            "attribute" => "intelligence",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/ancient_apparition.png"
        ],
        [
            "name" => "Doom",
            "attribute" => "strength",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/doom_bringer.png"
        ],
        [
            "name" => "Ursa",
            "attribute" => "agility",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/ursa.png"
        ],
        [
            "name" => "Spirit Breaker",
            "attribute" => "strength",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/spirit_breaker.png"
        ],
        [
            "name" => "Gyrocopter",
            "attribute" => "agility",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/gyrocopter.png"
        ],
        [
            "name" => "Alchemist",
            "attribute" => "strength",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/alchemist.png"
        ],
        [
            "name" => "Invoker",
            "attribute" => "intelligence",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/invoker.png"
        ],
        [
            "name" => "Silencer",
            "attribute" => "intelligence",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/silencer.png"
        ],
        [
            "name" => "Outworld Destroyer",
            "attribute" => "intelligence",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/obsidian_destroyer.png"
        ],
        [
            "name" => "Lycan",
            "attribute" => "strength",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/lycan.png"
        ],
        [
            "name" => "Brewmaster",
            "attribute" => "strength",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/brewmaster.png"
        ],
        [
            "name" => "Shadow Demon",
            "attribute" => "intelligence",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/shadow_demon.png"
        ],
        [
            "name" => "Lone Druid",
            "attribute" => "agility",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/lone_druid.png"
        ],
        [
            "name" => "Chaos Knight",
            "attribute" => "strength",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/chaos_knight.png"
        ],
        [
            "name" => "Meepo",
            "attribute" => "agility",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/meepo.png"
        ],
        [
            "name" => "Treant Protector",
            "attribute" => "strength",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/treant.png"
        ],
        [
            "name" => "Ogre Magi",
            "attribute" => "intelligence",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/ogre_magi.png"
        ],
        [
            "name" => "Undying",
            "attribute" => "strength",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/undying.png"
        ],
        [
            "name" => "Rubick",
            "attribute" => "intelligence",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/rubick.png"
        ],
        [
            "name" => "Disruptor",
            "attribute" => "intelligence",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/disruptor.png"
        ],
        [
            "name" => "Nyx Assassin",
            "attribute" => "agility",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/nyx_assassin.png"
        ],
        [
            "name" => "Naga Siren",
            "attribute" => "agility",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/naga_siren.png"
        ],
        [
            "name" => "Keeper of the Light",
            "attribute" => "intelligence",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/keeper_of_the_light.png"
        ],
        [
            "name" => "Io",
            "attribute" => "strength",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/wisp.png"
        ],
        [
            "name" => "Visage",
            "attribute" => "intelligence",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/visage.png"
        ],
        [
            "name" => "Slark",
            "attribute" => "agility",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/slark.png"
        ],
        [
            "name" => "Medusa",
            "attribute" => "agility",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/medusa.png"
        ],
        [
            "name" => "Troll Warlord",
            "attribute" => "agility",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/troll_warlord.png"
        ],
        [
            "name" => "Centaur Warrunner",
            "attribute" => "strength",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/centaur.png"
        ],
        [
            "name" => "Magnus",
            "attribute" => "strength",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/magnataur.png"
        ],
        [
            "name" => "Timbersaw",
            "attribute" => "strength",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/shredder.png"
        ],
        [
            "name" => "Bristleback",
            "attribute" => "strength",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/bristleback.png"
        ],
        [
            "name" => "Tusk",
            "attribute" => "strength",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/tusk.png"
        ],
        [
            "name" => "Skywrath Mage",
            "attribute" => "intelligence",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/skywrath_mage.png"
        ],
        [
            "name" => "Abaddon",
            "attribute" => "strength",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/abaddon.png"
        ],
        [
            "name" => "Elder Titan",
            "attribute" => "strength",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/elder_titan.png"
        ],
        [
            "name" => "Legion Commander",
            "attribute" => "strength",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/legion_commander.png"
        ],
        [
            "name" => "Techies",
            "attribute" => "intelligence",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/techies.png"
        ],
        [
            "name" => "Ember Spirit",
            "attribute" => "agility",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/ember_spirit.png"
        ],
        [
            "name" => "Earth Spirit",
            "attribute" => "strength",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/earth_spirit.png"
        ],
        [
            "name" => "Underlord",
            "attribute" => "strength",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/abyssal_underlord.png"
        ],
        [
            "name" => "Terrorblade",
            "attribute" => "agility",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/terrorblade.png"
        ],
        [
            "name" => "Phoenix",
            "attribute" => "strength",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/phoenix.png"
        ],
        [
            "name" => "Oracle",
            "attribute" => "intelligence",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/oracle.png"
        ],
        [
            "name" => "Winter Wyvern",
            "attribute" => "intelligence",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/winter_wyvern.png"
        ],
        [
            "name" => "Arc Warden",
            "attribute" => "agility",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/arc_warden.png"
        ],
        [
            "name" => "Monkey King",
            "attribute" => "agility",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/monkey_king.png"
        ],
        [
            "name" => "Dark Willow",
            "attribute" => "intelligence",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/dark_willow.png"
        ],
        [
            "name" => "Pangolier",
            "attribute" => "agility",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/pangolier.png"
        ],
        [
            "name" => "Grimstroke",
            "attribute" => "intelligence",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/grimstroke.png"
        ],
        [
            "name" => "Hoodwink",
            "attribute" => "agility",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/hoodwink.png"
        ],
        [
            "name" => "Void Spirit",
            "attribute" => "intelligence",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/void_spirit.png"
        ],
        [
            "name" => "Snapfire",
            "attribute" => "strength",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/snapfire.png"
        ],
        [
            "name" => "Mars",
            "attribute" => "strength",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/mars.png"
        ],
        [
            "name" => "Dawnbreaker",
            "attribute" => "strength",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/dawnbreaker.png"
        ],
        [
            "name" => "Marci",
            "attribute" => "strength",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/marci.png"
        ],
        [
            "name" => "Primal Beast",
            "attribute" => "strength",
            "thumbnail" => "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/primal_beast.png"
        ]
    ];

    // Generated by an older version of `artisan smarf:hero`
    protected $outdated = [
        [
            "name" => "Anti-Mage",
            "attribute" => "agility",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/antimage_full.png"
        ],
        [
            "name" => "Axe",
            "attribute" => "strength",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/axe_full.png"
        ],
        [
            "name" => "Bane",
            "attribute" => "intelligence",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/bane_full.png"
        ],
        [
            "name" => "Bloodseeker",
            "attribute" => "agility",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/bloodseeker_full.png"
        ],
        [
            "name" => "Crystal Maiden",
            "attribute" => "intelligence",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/crystal_maiden_full.png"
        ],
        [
            "name" => "Drow Ranger",
            "attribute" => "agility",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/drow_ranger_full.png"
        ],
        [
            "name" => "Earthshaker",
            "attribute" => "strength",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/earthshaker_full.png"
        ],
        [
            "name" => "Juggernaut",
            "attribute" => "agility",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/juggernaut_full.png"
        ],
        [
            "name" => "Mirana",
            "attribute" => "agility",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/mirana_full.png"
        ],
        [
            "name" => "Morphling",
            "attribute" => "agility",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/morphling_full.png"
        ],
        [
            "name" => "Shadow Fiend",
            "attribute" => "agility",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/nevermore_full.png"
        ],
        [
            "name" => "Phantom Lancer",
            "attribute" => "agility",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/phantom_lancer_full.png"
        ],
        [
            "name" => "Puck",
            "attribute" => "intelligence",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/puck_full.png"
        ],
        [
            "name" => "Pudge",
            "attribute" => "strength",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/pudge_full.png"
        ],
        [
            "name" => "Razor",
            "attribute" => "agility",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/razor_full.png"
        ],
        [
            "name" => "Sand King",
            "attribute" => "strength",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/sand_king_full.png"
        ],
        [
            "name" => "Storm Spirit",
            "attribute" => "intelligence",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/storm_spirit_full.png"
        ],
        [
            "name" => "Sven",
            "attribute" => "strength",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/sven_full.png"
        ],
        [
            "name" => "Tiny",
            "attribute" => "strength",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/tiny_full.png"
        ],
        [
            "name" => "Vengeful Spirit",
            "attribute" => "agility",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/vengefulspirit_full.png"
        ],
        [
            "name" => "Windranger",
            "attribute" => "intelligence",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/windrunner_full.png"
        ],
        [
            "name" => "Zeus",
            "attribute" => "intelligence",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/zuus_full.png"
        ],
        [
            "name" => "Kunkka",
            "attribute" => "strength",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/kunkka_full.png"
        ],
        [
            "name" => "Lina",
            "attribute" => "intelligence",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/lina_full.png"
        ],
        [
            "name" => "Lion",
            "attribute" => "intelligence",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/lion_full.png"
        ],
        [
            "name" => "Shadow Shaman",
            "attribute" => "intelligence",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/shadow_shaman_full.png"
        ],
        [
            "name" => "Slardar",
            "attribute" => "strength",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/slardar_full.png"
        ],
        [
            "name" => "Tidehunter",
            "attribute" => "strength",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/tidehunter_full.png"
        ],
        [
            "name" => "Witch Doctor",
            "attribute" => "intelligence",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/witch_doctor_full.png"
        ],
        [
            "name" => "Lich",
            "attribute" => "intelligence",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/lich_full.png"
        ],
        [
            "name" => "Riki",
            "attribute" => "agility",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/riki_full.png"
        ],
        [
            "name" => "Enigma",
            "attribute" => "intelligence",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/enigma_full.png"
        ],
        [
            "name" => "Tinker",
            "attribute" => "intelligence",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/tinker_full.png"
        ],
        [
            "name" => "Sniper",
            "attribute" => "agility",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/sniper_full.png"
        ],
        [
            "name" => "Necrophos",
            "attribute" => "intelligence",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/necrolyte_full.png"
        ],
        [
            "name" => "Warlock",
            "attribute" => "intelligence",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/warlock_full.png"
        ],
        [
            "name" => "Beastmaster",
            "attribute" => "strength",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/beastmaster_full.png"
        ],
        [
            "name" => "Queen of Pain",
            "attribute" => "intelligence",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/queenofpain_full.png"
        ],
        [
            "name" => "Venomancer",
            "attribute" => "agility",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/venomancer_full.png"
        ],
        [
            "name" => "Faceless Void",
            "attribute" => "agility",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/faceless_void_full.png"
        ],
        [
            "name" => "Wraith King",
            "attribute" => "strength",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/skeleton_king_full.png"
        ],
        [
            "name" => "Death Prophet",
            "attribute" => "intelligence",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/death_prophet_full.png"
        ],
        [
            "name" => "Phantom Assassin",
            "attribute" => "agility",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/phantom_assassin_full.png"
        ],
        [
            "name" => "Pugna",
            "attribute" => "intelligence",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/pugna_full.png"
        ],
        [
            "name" => "Templar Assassin",
            "attribute" => "agility",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/templar_assassin_full.png"
        ],
        [
            "name" => "Viper",
            "attribute" => "agility",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/viper_full.png"
        ],
        [
            "name" => "Luna",
            "attribute" => "agility",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/luna_full.png"
        ],
        [
            "name" => "Dragon Knight",
            "attribute" => "strength",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/dragon_knight_full.png"
        ],
        [
            "name" => "Dazzle",
            "attribute" => "intelligence",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/dazzle_full.png"
        ],
        [
            "name" => "Clockwerk",
            "attribute" => "strength",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/rattletrap_full.png"
        ],
        [
            "name" => "Leshrac",
            "attribute" => "intelligence",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/leshrac_full.png"
        ],
        [
            "name" => "Nature's Prophet",
            "attribute" => "intelligence",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/furion_full.png"
        ],
        [
            "name" => "Lifestealer",
            "attribute" => "strength",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/life_stealer_full.png"
        ],
        [
            "name" => "Dark Seer",
            "attribute" => "intelligence",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/dark_seer_full.png"
        ],
        [
            "name" => "Clinkz",
            "attribute" => "agility",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/clinkz_full.png"
        ],
        [
            "name" => "Omniknight",
            "attribute" => "strength",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/omniknight_full.png"
        ],
        [
            "name" => "Enchantress",
            "attribute" => "intelligence",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/enchantress_full.png"
        ],
        [
            "name" => "Huskar",
            "attribute" => "strength",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/huskar_full.png"
        ],
        [
            "name" => "Night Stalker",
            "attribute" => "strength",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/night_stalker_full.png"
        ],
        [
            "name" => "Broodmother",
            "attribute" => "agility",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/broodmother_full.png"
        ],
        [
            "name" => "Bounty Hunter",
            "attribute" => "agility",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/bounty_hunter_full.png"
        ],
        [
            "name" => "Weaver",
            "attribute" => "agility",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/weaver_full.png"
        ],
        [
            "name" => "Jakiro",
            "attribute" => "intelligence",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/jakiro_full.png"
        ],
        [
            "name" => "Batrider",
            "attribute" => "intelligence",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/batrider_full.png"
        ],
        [
            "name" => "Chen",
            "attribute" => "intelligence",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/chen_full.png"
        ],
        [
            "name" => "Spectre",
            "attribute" => "agility",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/spectre_full.png"
        ],
        [
            "name" => "Ancient Apparition",
            "attribute" => "intelligence",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/ancient_apparition_full.png"
        ],
        [
            "name" => "Doom",
            "attribute" => "strength",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/doom_bringer_full.png"
        ],
        [
            "name" => "Ursa",
            "attribute" => "agility",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/ursa_full.png"
        ],
        [
            "name" => "Spirit Breaker",
            "attribute" => "strength",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/spirit_breaker_full.png"
        ],
        [
            "name" => "Gyrocopter",
            "attribute" => "agility",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/gyrocopter_full.png"
        ],
        [
            "name" => "Alchemist",
            "attribute" => "strength",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/alchemist_full.png"
        ],
        [
            "name" => "Invoker",
            "attribute" => "intelligence",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/invoker_full.png"
        ],
        [
            "name" => "Silencer",
            "attribute" => "intelligence",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/silencer_full.png"
        ],
        [
            "name" => "Outworld Destroyer",
            "attribute" => "intelligence",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/obsidian_destroyer_full.png"
        ],
        [
            "name" => "Lycan",
            "attribute" => "strength",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/lycan_full.png"
        ],
        [
            "name" => "Brewmaster",
            "attribute" => "strength",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/brewmaster_full.png"
        ],
        [
            "name" => "Shadow Demon",
            "attribute" => "intelligence",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/shadow_demon_full.png"
        ],
        [
            "name" => "Lone Druid",
            "attribute" => "agility",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/lone_druid_full.png"
        ],
        [
            "name" => "Chaos Knight",
            "attribute" => "strength",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/chaos_knight_full.png"
        ],
        [
            "name" => "Meepo",
            "attribute" => "agility",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/meepo_full.png"
        ],
        [
            "name" => "Treant Protector",
            "attribute" => "strength",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/treant_full.png"
        ],
        [
            "name" => "Ogre Magi",
            "attribute" => "intelligence",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/ogre_magi_full.png"
        ],
        [
            "name" => "Undying",
            "attribute" => "strength",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/undying_full.png"
        ],
        [
            "name" => "Rubick",
            "attribute" => "intelligence",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/rubick_full.png"
        ],
        [
            "name" => "Disruptor",
            "attribute" => "intelligence",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/disruptor_full.png"
        ],
        [
            "name" => "Nyx Assassin",
            "attribute" => "agility",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/nyx_assassin_full.png"
        ],
        [
            "name" => "Naga Siren",
            "attribute" => "agility",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/naga_siren_full.png"
        ],
        [
            "name" => "Keeper of the Light",
            "attribute" => "intelligence",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/keeper_of_the_light_full.png"
        ],
        [
            "name" => "Io",
            "attribute" => "strength",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/wisp_full.png"
        ],
        [
            "name" => "Visage",
            "attribute" => "intelligence",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/visage_full.png"
        ],
        [
            "name" => "Slark",
            "attribute" => "agility",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/slark_full.png"
        ],
        [
            "name" => "Medusa",
            "attribute" => "agility",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/medusa_full.png"
        ],
        [
            "name" => "Troll Warlord",
            "attribute" => "agility",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/troll_warlord_full.png"
        ],
        [
            "name" => "Centaur Warrunner",
            "attribute" => "strength",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/centaur_full.png"
        ],
        [
            "name" => "Magnus",
            "attribute" => "strength",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/magnataur_full.png"
        ],
        [
            "name" => "Timbersaw",
            "attribute" => "strength",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/shredder_full.png"
        ],
        [
            "name" => "Bristleback",
            "attribute" => "strength",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/bristleback_full.png"
        ],
        [
            "name" => "Tusk",
            "attribute" => "strength",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/tusk_full.png"
        ],
        [
            "name" => "Skywrath Mage",
            "attribute" => "intelligence",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/skywrath_mage_full.png"
        ],
        [
            "name" => "Abaddon",
            "attribute" => "strength",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/abaddon_full.png"
        ],
        [
            "name" => "Elder Titan",
            "attribute" => "strength",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/elder_titan_full.png"
        ],
        [
            "name" => "Legion Commander",
            "attribute" => "strength",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/legion_commander_full.png"
        ],
        [
            "name" => "Techies",
            "attribute" => "intelligence",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/techies_full.png"
        ],
        [
            "name" => "Ember Spirit",
            "attribute" => "agility",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/ember_spirit_full.png"
        ],
        [
            "name" => "Earth Spirit",
            "attribute" => "strength",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/earth_spirit_full.png"
        ],
        [
            "name" => "Underlord",
            "attribute" => "strength",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/abyssal_underlord_full.png"
        ],
        [
            "name" => "Terrorblade",
            "attribute" => "agility",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/terrorblade_full.png"
        ],
        [
            "name" => "Phoenix",
            "attribute" => "strength",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/phoenix_full.png"
        ],
        [
            "name" => "Oracle",
            "attribute" => "intelligence",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/oracle_full.png"
        ],
        [
            "name" => "Winter Wyvern",
            "attribute" => "intelligence",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/winter_wyvern_full.png"
        ],
        [
            "name" => "Arc Warden",
            "attribute" => "agility",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/arc_warden_full.png"
        ],
        [
            "name" => "Monkey King",
            "attribute" => "agility",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/monkey_king_full.png"
        ],
        [
            "name" => "Dark Willow",
            "attribute" => "intelligence",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/dark_willow_full.png"
        ],
        [
            "name" => "Pangolier",
            "attribute" => "agility",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/pangolier_full.png"
        ],
        [
            "name" => "Grimstroke",
            "attribute" => "intelligence",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/grimstroke_full.png"
        ],
        [
            "name" => "Hoodwink",
            "attribute" => "agility",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/hoodwink_full.png"
        ],
        [
            "name" => "Void Spirit",
            "attribute" => "intelligence",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/void_spirit_full.png"
        ],
        [
            "name" => "Snapfire",
            "attribute" => "strength",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/snapfire_full.png"
        ],
        [
            "name" => "Mars",
            "attribute" => "strength",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/mars_full.png"
        ],
        [
            "name" => "Dawnbreaker",
            "attribute" => "strength",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/dawnbreaker_full.png"
        ],
        [
            "name" => "Marci",
            "attribute" => "strength",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/marci_full.png"
        ],
        [
            "name" => "Primal Beast",
            "attribute" => "strength",
            "thumbnail" => "https://cdn.dota2.com/apps/dota2/images/heroes/primal_beast_full.png"
        ]
    ];

    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        collect($this->updated)->each(function ($hero) {
            Hero::where('name', $hero['name'])->update(['thumbnail' => $hero['thumbnail']]);
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        collect($this->outdated)->each(function ($hero) {
            Hero::where('name', $hero['name'])->update(['thumbnail' => $hero['thumbnail']]);
        });
    }
};
